apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    # add these required labels
    prometheus: k8s-prometheus
    role: alert-rules
  name: service-metrics
  # put it in your namespace
  namespace: sample
spec:
  groups:
    # name the group such that there's no collision with other rules
    # in other namespaces
    - name: intuit.identity-privacy-token-usw2-ppd-prf.token.health.rules
      rules:
        - expr: rate(http_server_requests_seconds_count[1m])
          # with metrics in other namespaces
          record: identity_privacy_token_availability_metrics
          # add this label if you want to also send this metric to wavefront
          labels:
            intuit_alert: "true"
